SecureDev/Controllers/EditProfileController.cs
using System;
using System.Collections.Generic;
using System.Data.SQLite;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Vladi2.App_Start;
using Vladi2.Models;
using Microsoft.Security.Application;

namespace Vladi2.Controllers
{
    [AuthAttr]
    public class EditProfileController : BaseController
    {
        public ActionResult Index()
        {
            return View((User)Session["myUser"]);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(User user, HttpPostedFileBase file)
        {
            UserResult result = user.UpdateProfile(file);

            if (result.Status == UserResult.Statuses.NotValidFirstName)
            {
                ViewBag.firstNameErr = result.Message;
                return View(user);
            }
            else
                ViewBag.firstNameErr = null;

            if (result.Status == UserResult.Statuses.NotValidLastName)
            {
                ViewBag.lastNameErr = result.Message;
                return View(user);
            }
            else
                ViewBag.lastNameErr = null;

            if (result.Status == UserResult.Statuses.NotValidEmail)
            {
                ViewBag.emailErr = result.Message;
                return View(user);
            }
            else
                ViewBag.emailErr = null;

            if (result.Status == UserResult.Statuses.NotValidPhone)
            {
                ViewBag.phoneErr = result.Message;
                return View(user);
            }
            else
                ViewBag.phoneErr = null;

            if (result.Status == UserResult.Statuses.NotValidFile)
            {
                ViewBag.imageErr = result.Message;
                return View(user);
            }
            else
                ViewBag.imageErr = null;

            return RedirectToAction("Index", "Profile");
        }
    }
}

SecureDev/Views/EditProfile/Index.cshtml
@using Vladi2.Models
@model User

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit Profile</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    @using (Html.BeginForm("Index", "EditProfile", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-centered toppad">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title">Edit Profile</h3>
                        </div>

                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-5 col-lg-5" align="center">
                                    <div class="user-img" id="img-preview" style="background-image: url('@Url.Content(((User)Session["myUser"]).PictureUrl)')"></div>
                                </div>
                                <div class="col-md-5 col-lg-5 " align="right" style="padding-top: 50px;">
                                    <input type="file" name="file" id="file" style="width: 200px;" />
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-11 col-centered">
                                    <table class="table table-user-information">
                                        <tbody>
                                            @if (ViewBag.imageErr != null)
                                            {
                                                <tr>
                                                    <td colspan="2">
                                                        <div class="alert alert-danger">
                                                            @ViewBag.imageErr
                                                        </div>
                                                    </td>
                                                </tr>
                                            }
                                            <tr>
                                                <td>First Name:</td>
                                                <td>
                                                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @Value = Model.FirstName } })
                                                </td>
                                            </tr>
                                            @if (ViewBag.firstNameErr != null)
                                            {
                                                <tr>
                                                    <td colspan="2">
                                                        <div class="alert alert-danger">
                                                            @ViewBag.firstNameErr
                                                        </div>
                                                    </td>
                                                </tr>
                                            }
                                            <tr>
                                                <td>Last Name:</td>
                                                <td>
                                                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @Value = Model.LastName } })
                                                </td>
                                            </tr>
                                            @if (ViewBag.lastNameErr != null)
                                            {
                                                <tr>
                                                    <td colspan="2">
                                                        <div class="alert alert-danger">
                                                            @ViewBag.lastNameErr
                                                        </div>
                                                    </td>
                                                </tr>
                                            }
                                            <tr>
                                                <td>Email:</td>
                                                <td>@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @Value = Model.Email } })</td>
                                            </tr>

                                            @if (ViewBag.emailErr != null)
                                            {
                                                <tr>
                                                    <td colspan="2">
                                                        <div class="alert alert-danger">
                                                            @ViewBag.emailErr
                                                        </div>
                                                    </td>
                                                </tr>
                                            }

                                            <tr>
                                                <td>Phone Number:</td>
                                                <td>@Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", @Value = Model.Phone } })</td>
                                            </tr>

                                            @if (ViewBag.phoneErr != null)
                                            {
                                                <tr>
                                                    <td colspan="2">
                                                        <div class="alert alert-danger">
                                                            @ViewBag.phoneErr
                                                        </div>
                                                    </td>
                                                </tr>
                                            }

                                            <tr>
                                                <td colspan="2">
                                                    <div class="col-md-5">
                                                        <input type="submit" value="Update" class="btn btn-primary btn-block" />
                                                    </div>
                                                    <div class="col-md-5">
                                                        @Html.ActionLink("Cancel", "Index", "Profile", null, new { @class = "btn btn-danger btn-block" })
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>