SecureDev/Controllers/AdminUsersController.cs
using Microsoft.Security.Application;
using System;
using System.Collections.Generic;
using System.Data.SQLite;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vladi2.App_Start;
using Vladi2.Helpers;
using Vladi2.Models;

namespace Vladi2.Controllers
{
    [AuthAttr(OnlyAdmin = true)]
    public class AdminUsersController : BaseController
    {
        public ActionResult Index()
        {
            List<User> usersList = new List<User>();

            try
            {
                var connectionString = string.Format("DataSource={0}", Server.MapPath(@"~\Sqlite\db.sqlite"));
                using (var m_dbConnection = new SQLiteConnection(connectionString))
                {
                    m_dbConnection.Open();
                    SQLiteCommand usersCommand = new SQLiteCommand(@"SELECT userName, firstName, lastName, email, phone, pictureUrl, isAdmin 
                                                                 FROM Users
                                                                 WHERE userName != @user
                                                                 ORDER BY userName COLLATE NOCASE ASC", m_dbConnection);

                    usersCommand.Parameters.Add(new SQLiteParameter("user", (Session["myUser"] as User).UserName));
                    using (SQLiteDataReader reader = usersCommand.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            usersList.Add(new User()
                            {
                                UserName = reader["userName"].ToString(),
                                FirstName = reader["firstName"].ToString(),
                                Email = reader["email"].ToString(),
                                Phone = reader["phone"].ToString(),
                                LastName = reader["lastName"].ToString(),
                                IsAdmin = reader["isAdmin"].ToString() == "1",
                                PictureUrl = reader["pictureUrl"].ToString()
                            });
                        }
                    }
                }
            }
            catch (SQLiteException)
            {
                Logger.WriteToLog(Logger.SQLLiteMsg);
                throw;
            }
            catch (Exception exception)
            {
                Logger.WriteToLog(exception);
                throw;
            }

            return View(usersList);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult changeUsersPrivileges(List<User> usersList)
        {
            Models.User.changeUsersPrivileges(usersList);

            return RedirectToAction("Index", "Admin");
        }
    }
}

SecureDev/Views/AdminUsers/Index.cshtml
@model List<Vladi2.Models.User>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Users</h2>

@using (Html.BeginForm("changeUsersPrivileges", "AdminUsers", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <table class="table">
        <tr>
            <th width="1">#</th>
            <th>
                @Html.DisplayNameFor(model => model[0].UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].IsAdmin)
            </th>
        </tr>

    @for (var i = 0; i < Model.Count; i++)
    {
        <tr>
            <td>
                <div class="disc-img" style="background-image: url('@Url.Content(@Model[i].PictureUrl)')"></div>
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem[i].UserName)
                @Html.HiddenFor(modelItem => modelItem[i].UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem[i].FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem[i].LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem[i].Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem[i].Phone)
            </td>
            <td>
                @Html.CheckBoxFor(modelItem => modelItem[i].IsAdmin)
            </td>

        </tr>
    }
        </table>

    <div class="row">
        <div class="col-md-1">
            <input type="submit" value="Update" class="btn btn-primary btn-block" />
        </div>
    </div>

}

<style>
    .table > tbody > tr > td {
        vertical-align: middle;
        text-align:center;
    }

    .table > tbody > tr > th {
        vertical-align: middle;
        text-align: center;
    }
</style>