SecureDev/Controllers/AdminDiscController.cs
using System;
using System.Collections.Generic;
using System.Data.SQLite;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Microsoft.Security.Application;
using Vladi2.App_Start;
using Vladi2.Helpers;
using Vladi2.Models;

namespace Vladi2.Controllers
{
    [AuthAttr(OnlyAdmin = true)]
    public class AdminDiscController : BaseController
    {
        private List<Category> GetCategories()
        {
            List<Category> categories = new List<Category>();
            try
            {
                var connectionString = string.Format("DataSource={0}", Server.MapPath(@"~\Sqlite\db.sqlite"));
                using (var m_dbConnection = new SQLiteConnection(connectionString))
                {
                    m_dbConnection.Open();
                    SQLiteCommand categoriesCdCommand = new SQLiteCommand(
                        @"select categoryName,categoryid from category",
                        m_dbConnection);
                    using (SQLiteDataReader reader = categoriesCdCommand.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            categories.Add(new Category()
                            {
                                CategoryID = int.Parse(reader["categoryid"].ToString()),
                                CategoryName = reader["categoryName"].ToString()
                            });
                        }
                    }
                }
                return categories;
            }
            catch (SQLiteException)
            {
                Logger.WriteToLog(Logger.SQLLiteMsg);
                throw;
            }
            catch (Exception exception)
            {
                Logger.WriteToLog(exception);
                throw;
            }
        }

        // GET: AdminDisc
        public ActionResult Index()
        {
            List<Disc> list = new List<Disc>();
            try
            {
                var connectionString = string.Format("DataSource={0}", Server.MapPath(@"~\Sqlite\db.sqlite"));
                using (var m_dbConnection = new SQLiteConnection(connectionString))
                {
                    m_dbConnection.Open();
                    SQLiteCommand storeCdCommand = new SQLiteCommand(
                        @"select Disc.discID,Disc.name,Disc.artist,Category.categoryName,added,Disc.pictureUrl,Disc.price,duration,songsamount from Disc 
                                INNER JOIN Category on Category.categoryid = Disc.categoryid order by datetime(added, 'localtime') desc",
                        m_dbConnection);
                    using (SQLiteDataReader reader = storeCdCommand.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            list.Add(new Disc()
                            {
                                DiscID = int.Parse(reader["discid"].ToString()),
                                Name = reader["name"].ToString(),
                                Artist = reader["artist"].ToString(),
                                Category = new Category() {CategoryName = reader["categoryname"].ToString()},
                                PictureUrl = reader["pictureurl"].ToString(),
                                Price = float.Parse(reader["price"].ToString()),
                                DiscAdded = DateTime.Parse(reader["added"].ToString()),
                                Duration = reader["duration"].ToString(),
                                SongsAmount = int.Parse(reader["songsamount"].ToString())
                            });
                        }
                    }
                }
                return View(list);
            }
            catch (SQLiteException)
            {
                Logger.WriteToLog(Logger.SQLLiteMsg);
                throw;
            }
            catch (Exception exception)
            {
                Logger.WriteToLog(exception);
                throw;
            }
        }

        public ActionResult Create()
        {
            ViewBag.Categories = GetCategories();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Disc disc, HttpPostedFileBase file)
        {
            try
            {
                bool isValid = ValidForm(disc, file);
                if (!isValid)
                    return View(disc);
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName).ToLower();
                    string path = Path.Combine(Server.MapPath(@"~\CD_Images\"), fileName);
                    file.SaveAs(path);
                    disc.PictureUrl = fileName;
                }
                else
                {
                    disc.PictureUrl = "no-image.png";
                }
                var connectionString = string.Format("DataSource={0}", Server.MapPath(@"~\Sqlite\db.sqlite"));
                using (var m_dbConnection = new SQLiteConnection(connectionString))
                {
                    m_dbConnection.Open();
                    SQLiteCommand createDiscCommand = new SQLiteCommand(
                        @"insert into disc (name,artist,categoryid,pictureurl,price,duration,songsamount,added)
                                        values (@name,@artist,@categoryid,@pictureurl,@price,@duration,@songsamount,@added)",
                        m_dbConnection);
                    createDiscCommand.Parameters.Add(new SQLiteParameter("name", disc.Name));
                    createDiscCommand.Parameters.Add(new SQLiteParameter("artist", disc.Artist));
                    createDiscCommand.Parameters.Add(new SQLiteParameter("categoryid", disc.Category.CategoryID));
                    createDiscCommand.Parameters.Add(new SQLiteParameter("pictureurl", disc.PictureUrl));
                    createDiscCommand.Parameters.Add(new SQLiteParameter("price", disc.Price));
                    createDiscCommand.Parameters.Add(new SQLiteParameter("duration", disc.Duration));
                    createDiscCommand.Parameters.Add(new SQLiteParameter("songsamount", disc.SongsAmount));
                    createDiscCommand.Parameters.Add(new SQLiteParameter("added", DateTime.Now));
                    createDiscCommand.ExecuteNonQuery();
                }
                return RedirectToAction("Index");
            }
            catch (SQLiteException)
            {
                Logger.WriteToLog(Logger.SQLLiteMsg);
                throw;
            }
            catch (Exception exception)
            {
                Logger.WriteToLog(exception);
                throw;
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                var connectionString = string.Format("DataSource={0}", Server.MapPath(@"~\Sqlite\db.sqlite"));
                using (var m_dbConnection = new SQLiteConnection(connectionString))
                {
                    m_dbConnection.Open();

                    SQLiteCommand discCdCommand = new SQLiteCommand(@"select pictureUrl from Disc where discid=@discid",
                        m_dbConnection);
                    discCdCommand.Parameters.Add(new SQLiteParameter("discid", id));
                    string image = discCdCommand.ExecuteScalar().ToString();
                    string path = Path.Combine(Server.MapPath(@"~\CD_Images\"), image);
                    if (System.IO.File.Exists(path) && image != "no-image.png")
                        System.IO.File.Delete(path);

                    SQLiteCommand deleteDiscCommand = new SQLiteCommand(@"delete from disc where discid=@discid",
                        m_dbConnection);
                    deleteDiscCommand.Parameters.Add(new SQLiteParameter("discid", id));
                    deleteDiscCommand.ExecuteNonQuery();
                }
                return RedirectToAction("Index");
            }
            catch (SQLiteException)
            {
                Logger.WriteToLog(Logger.SQLLiteMsg);
                throw;
            }
            catch (Exception exception)
            {
                Logger.WriteToLog(exception);
                throw;
            }
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Categories = GetCategories();
            try
            {
                var connectionString = string.Format("DataSource={0}", Server.MapPath(@"~\Sqlite\db.sqlite"));
                using (var m_dbConnection = new SQLiteConnection(connectionString))
                {
                    m_dbConnection.Open();
                    SQLiteCommand discCdCommand =
                        new SQLiteCommand(
                            @"select Disc.discID,Disc.name,Disc.artist,Category.categoryid,Disc.pictureUrl,Disc.price,added,duration,songsamount from Disc 
                                INNER JOIN Category on Category.categoryid = Disc.categoryid where discid=@discid",
                            m_dbConnection);
                    discCdCommand.Parameters.Add(new SQLiteParameter("discid", id));
                    using (SQLiteDataReader reader = discCdCommand.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            return View(new Disc()
                            {
                                DiscID = int.Parse(reader["discid"].ToString()),
                                Name = reader["name"].ToString(),

SecureDev/Views/AdminDisc/Create.cshtml
@model Vladi2.Models.Disc

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Create", "AdminDisc", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "box-form" }))
{
    <h4>Create New Disc</h4>

    @Html.AntiForgeryToken()
    <hr />
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        
        @if (ViewBag.nameErr != null)
        {
            <div class="form-group alert alert-danger">
                @ViewBag.nameErr
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Artist, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Artist, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        
        @if (ViewBag.artistErr != null)
        {
            <div class="form-group alert alert-danger">
                @ViewBag.artistErr
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        
        @if (ViewBag.priceErr != null)
        {
            <div class="form-group alert alert-danger">
                @ViewBag.priceErr
            </div>
        }


        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        
        @if (ViewBag.durationErr != null)
        {
            <div class="form-group alert alert-danger">
                @ViewBag.durationErr
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.SongsAmount, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.SongsAmount, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        
        @if (ViewBag.amountErr != null)
        {
            <div class="form-group alert alert-danger">
                @ViewBag.amountErr
            </div>
        }
        
        <div class="form-group">
            <label class="control-label col-md-3">Category</label>
            <div class="col-md-3">
                @Html.DropDownListFor(x => x.Category.CategoryID, new SelectList(ViewBag.Categories, "CategoryID", "CategoryName"))
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-3" align="center">
                <div class="disc-img" style="background-image: url('/CD_Images/no-image.png')" id="img-preview"></div>
            </div>
        </div>
        @if (ViewBag.imageErr != null)
        {
            <div class="form-group alert alert-danger">
                @ViewBag.imageErr
            </div>
        }
        

        <div class="form-group">
            <div class="col-md-1" align="right">
                <input type="file" name="file" id="file" style="width: 200px;" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                <input type="reset" value="Clear" class="btn btn-danger" />
            </div>
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SecureDev/Views/AdminDisc/Edit.cshtml
@model Vladi2.Models.Disc

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Edit", "AdminDisc", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "box-form" }))
{
    <h4>Edit Disc</h4>

    @Html.AntiForgeryToken()
    <hr />
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        @if (ViewBag.nameErr != null)
        {
            <div class="form-group alert alert-danger">
                @ViewBag.nameErr
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Artist, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Artist, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        @if (ViewBag.artistErr != null)
        {
            <div class="form-group alert alert-danger">
                @ViewBag.artistErr
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        @if (ViewBag.priceErr != null)
        {
            <div class="form-group alert alert-danger">
                @ViewBag.priceErr
            </div>
        }


        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        @if (ViewBag.durationErr != null)
        {
            <div class="form-group alert alert-danger">
                @ViewBag.durationErr
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.SongsAmount, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.SongsAmount, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        @if (ViewBag.amountErr != null)
        {
            <div class="form-group alert alert-danger">
                @ViewBag.amountErr
            </div>
        }

        <div class="form-group">
            <label class="control-label col-md-3">Category</label>
            <div class="col-md-3">
                @Html.DropDownListFor(x => x.Category.CategoryID, new SelectList(ViewBag.Categories, "CategoryID", "CategoryName"))
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-3" align="center">
                <div class="disc-img" style="background-image: url('@Url.Content("~/CD_Images/"+@Model.PictureUrl)')" id="img-preview"></div>
            </div>
        </div>
        @if (ViewBag.imageErr != null)
        {
            <div class="form-group alert alert-danger">
                @ViewBag.imageErr
            </div>
        }
        @Html.HiddenFor(item => item.PictureUrl)
        @Html.HiddenFor(item=>item.DiscID)

        <div class="form-group">
            <div class="col-md-1" align="right">
                <input type="file" name="file" id="file" style="width: 200px;" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Update" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index","AdminDisc",null,new {@class="btn btn-danger"})
            </div>
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SecureDev/Views/AdminDisc/Index.cshtml
@model IEnumerable<Vladi2.Models.Disc>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Discs</h2>

<p>
    @Html.ActionLink("Create New", "Create","AdminDisc",new {@class="btn btn-primary"})
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Artist)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DiscAdded)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SongsAmount)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                <div class="disc-img" style="background-image: url('CD_Images/@item.PictureUrl')"></div>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Artist)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiscAdded)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SongsAmount)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = item.DiscID}) |
                @Html.ActionLink("View", "ViewDisc", "Store", new { id = item.DiscID }, null) |
                @Html.ActionLink("Delete", "Delete", new {id = item.DiscID},new { onclick = "return confirm('Are you sure?');" })
            </td>
        </tr>
    }

</table>